openapi: "3.0.0"
info:
  version: 1.0.0
  title: Admin API
paths:
  /users:
    get:
      summary: Return all users
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    password:
                      type: string
                  required:
                    - id
