name: "Update OpenAPI specifications and raise PRs if changes needed"
permissions:
  contents: write
  pull-requests: write
on:
  push: {}
  workflow_dispatch: {}
  # NOTE that this would ideally be done in a schedule
jobs:
  sync-petstore:
    uses: jamietanna/actions/.github/workflows/reusable-sync-file.yml@feature/sync-files
    with:
      identifier: oapi-codegen-petstore
      remote_slug: deepmap/oapi-codegen
      remote_path: examples/petstore-expanded/petstore-expanded.yaml
      local_path: petstore.yaml
    secrets:
      # as this is a public repo, we can sync it easily with the inbuilt token
      cross_repo_github_token: ${{ secrets.GITHUB_TOKEN }}

    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v3
    #
    #   - name: Fetch Petstore's latest OpenAPI
    #     run: |
    #       set -o pipefail
    #       gh api /repos/deepmap/oapi-codegen/contents/ --template '{{ .content }}' | base64 -d > head.yaml
    #     env:
    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #
    #   - name: "Is Petstore's OpenAPI up-to-date?"
    #     run: |
    #       git diff --color --no-index petstore.yaml head.yaml || \
    #         echo "::warning file=petstore.yaml::File is out-of-sync with upstream repo"
    #
